#include QMK_KEYBOARD_H

void eeconfig_init_user(void) {
    set_unicode_input_mode(UC_MAC);
}

enum unicode_names {
    AEL,
    AEU,
    OEL,
    OEU,
	UEL,
    UEU,
	SSL,
    SSU,
	PARA,
    EURO,
    DEG
};

const uint32_t PROGMEM unicode_map[] = {
    [AEL]	= 0x00E4, // 0
    [AEU]	= 0x00C4, // 1
    [OEL]	= 0x00F6, // 2
    [OEU]	= 0x00D6, // 3
	[UEL]	= 0x00FC, // 4
    [UEU]	= 0x00DC, // 5
	[SSL]	= 0x00DF, // 6
    [SSU]	= 0x1e9e, // 7
	[PARA]	= 0x00A7, // 8
    [EURO]	= 0x20ac, // 9
    [DEG]   = 0x00B0  // 10
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_60_iso(KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_EQL, KC_BSPC, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, KC_RBRC, LT(1, KC_RIGHT), KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_BSLS, KC_ENT, LSFT_T(KC_LEFT_PAREN), KC_GRV, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, RSFT(KC_RIGHT_PAREN), KC_LCTL, KC_LALT, KC_LGUI, KC_SPC, RGUI_T(KC_LEFT), LT(1, KC_DOWN), LT(2, KC_UP), RALT_T(KC_RIGHT)),
	[1] = LAYOUT_60_iso(TG(1), KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_DEL, KC_TRNS, KC_TRNS, KC_TRNS, X(9), KC_TRNS, KC_TRNS, KC_TRNS, XP(4, 5), KC_UP, XP(2, 3), X(8), KC_TRNS, KC_TRNS, KC_TRNS, XP(0, 1), XP(6, 7), KC_TRNS, KC_TRNS, KC_TRNS, KC_HOME, KC_LEFT, KC_DOWN, KC_RGHT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, X(10), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_PGUP, KC_END, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_PGDN, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[2] = LAYOUT_60_iso(TG(2), KC_F13, KC_F14, KC_F15, KC_F16, KC_F17, KC_F18, KC_F19, KC_F20, KC_F21, KC_F22, KC_F23, KC_F24, KC_TRNS, KC_TRNS, KC_TRNS, KC_UP, KC_TRNS, KC_TRNS, KC_TRNS, KC_WH_U, KC_BTN1, KC_MS_U, KC_BTN2, KC_BTN3, KC_BTN4, KC_BTN5, KC_TRNS, KC_LEFT, KC_DOWN, KC_RGHT, KC_TRNS, KC_TRNS, KC_WH_D, KC_MS_L, KC_MS_D, KC_MS_R, KC_ACL0, KC_ACL1, KC_ACL2, KC_TRNS, KC_VOLU, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_VOLD, KC_MUTE, KC_MPRV, KC_MPLY, KC_MNXT, KC_TRNS, KC_TRNS, KC_TRNS)
};
